In [825]:
import pandas as pd 
from sklearn import datasets
from sklearn.utils import shuffle
import sklearn.metrics as metrics
iris = datasets.load_iris()

In [ ]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [827]:
df = shuffle(df)
df.reset_index(inplace=True, drop=True)
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.0,3.4,1.5,0.2,0
1,5.7,2.6,3.5,1.0,1
2,6.2,2.8,4.8,1.8,2
3,6.9,3.1,5.4,2.1,2
4,5.0,3.2,1.2,0.2,0

In [828]:
class KNN():

    def __init__(self, df, k, sep, len):
        
        self.k = k
        train, test = df.iloc[0:sep], df.iloc[sep+1:len+1]
        self.X_train, self.X_test, self.y_train, self.y_test = train.drop(["target"], axis=1), test.drop(["target"], axis=1), train[["target"]], test[["target"]]

    def fit_and_predict(self):
        
        y_pred = self.y_test.copy()

        for i, row in self.X_test.iterrows():
            temp_train = self.X_train - row
            temp_train = temp_train.pow(2)
            temp_train["sum"] = temp_train.sum(axis=1)
            temp_train = temp_train.sort_values("sum")
            m = self.y_train.loc[temp_train.index[:self.k]].mode()["target"][0]
            y_pred.loc[i] = m

        return y_pred
    
    def score(self):

        preds = self.fit_and_predict()
        acc = (preds == self.y_test)
        return acc.mean()

In [829]:
iris_classifier = KNN(df, 5, 80, 100)
iris_classifier.score()

target    0.95
dtype: float64